apiVersion: v1
kind: Service
metadata:
  name: {{ include "bcchart.fullname" . }}-nginxservice
  labels:
    {{- include "bcchart.labels" . | nindent 4 }}
    tier: frontend
spec:
  type: {{ .Values.nginxservice.type }}
  ports:
    - port: {{ .Values.nginxservice.port }}
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    {{- include "bcchart.selectorLabels" . | nindent 4 }}
    tier: frontend
  type: {{ .Values.nginxservice.type }}
  loadBalancerSourceRanges:
    - "89.41.48.0/24"
