FROM --platform=linux/amd64 node:18 as build

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install

FROM build as run

ENV DB_URL=/db/books_23.db

COPY . .

EXPOSE 3000

CMD ["node", "bin/www"]